# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: false
cache: packages

#matrix: 3x Linux, 1x OS X
matrix:
  include:
  - r: release
  - r: oldrel
  - r: devel
  - os: osx
    r: release
    latex: false

r_packages:
   - testthat
   - reticulate
   - dplyr
   - reticulate
   - tibble
   - purrr
   - lubridate
   - tibble

r_github_packages:
  - fdrennan/awsR

after_success:
  - Rscript -e 'covr::codecov()'


