# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
warnings_are_errors: false
sudo: false
dist: trusty
cache: packages

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - pip install --upgrade --ignore-installed --user travis virtualenv
  - R CMD INSTALL .
  - virtualenv -p /usr/bin/python3 venv
  - source venv/bin/activate
  - pip3 install numpy scipy awscli boto3

env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
   - testthat
   - reticulate
   - dplyr
   - reticulate
   - tibble
   - purrr
   - lubridate
   - tibble


