# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
warnings_are_errors: false
sudo: false
dist: trusty
cache: packages

before_install:
  - pip install --user numpy scipy awscli boto3

env:
 global:
   - CRAN: http://cran.rstudio.com

matrix:
  include:
  - r: devel
  - r: release
  - r: oldrel

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov(token = "8f1f8ab4-c78c-478a-9522-9ec3b6dd1d90")'

r_packages:
   - testthat
   - reticulate
   - dplyr
   - reticulate
   - tibble
   - purrr
   - lubridate
