# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: false
sudo: required
dist: xenial
cache: packages

before_install:
  - pip install numpy scipy awscli boto3

env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
   - testthat
   - reticulate
   - dplyr
   - reticulate
   - tibble
   - purrr
   - lubridate
   - tibble


