version: '3.3'
services:
  db:
   image: "postgres"
   container_name: "ndexr_postgres"
   restart: always
   ports:
     - '5432:5432'
   expose:
      # Opens port 5432 on the container
     - '5432'
    # Where our data will be persisted
   volumes:
     - ndexr_postgres_data:/var/lib/postgresql/data
   environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB:'postgres'
volumes:
  ndexr_postgres_data:
